config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :markets, only: [:index, :show]
  resources :vendors, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    market_facade = MarketsFacade.new
    @markets = market_facade.list_markets
  end

  def show
    market_facade = MarketsFacade.new
    @market = market_facade.find_market(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    vendors_facade = VendorsFacade.new
    @vendor = vendors_facade.find_vendor(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<table>
  <tr>
    <th>Name </th>
    <th>City </th>
    <th>State </th>
    <th> </th>
  </tr>
  <% @markets.each do |market| %>
    <tr id='<%= market.id %>-index'>
      <td><%= market.name %></td>
      <td><%= market.city %></td>
      <td><%= market.state %></td>
      <td><%= button_to 'More Info', "/markets/#{market.id}", method: :get %></td>
    </tr>
  <% end %>
</table>

app/views/markets/show.html.erb
<h1><%= @market.name %></h1>
<h3><%= @market.street %></h3>
<h3><%= @market.city %>, <%= @market.state %> <%= @market.zip %></h3>

<h4>Vendors at our Market: </h3>
<li>
  <% @market.vendors.each do |vendor| %>
    <%= link_to vendor.name, vendor_path(vendor.id) %>
  <% end %>
</li>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>
<h4>Contact Info: </h4>
<h4>name: <%= @vendor.contact_name %></h4>
<h4>phone: <%= @vendor.contact_phone %></h4>
<h4>Credit Accepted? <%= @vendor.credit_accepted %></h4>
<h4>Description: <%= @vendor.description %></h4>